# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sdarron <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/08 17:46:00 by sdarron           #+#    #+#              #
#    Updated: 2019/09/13 15:47:16 by sdarron          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

SRCS = ft_display_file.c

OBJ = ft_display_file.o

all:
		gcc -c $(SRCS)
		gcc -o $(NAME) $(OBJ)

clean: 
		rm -f $(OBJ)

fclean: clean
		rm -f $(NAME)
